#!/bin/bash

# Nama berkas CSV untuk menyimpan data
data_file="data.csv"

# Memeriksa apakah berkas sudah ada, jika tidak, membuatnya
if [ ! -e "$data_file" ]; then
  echo "NIK,Nama,Tempat Tanggal Lahir,Jenis Kelamin,Alamat,Agama,Status Perkawinan,Pekerjaan,Kewarganegaraan,Berlaku Hingga" > "$data_file"
fi

# Membaca data yang sudah ada dari berkas
data_existing=$(cat "$data_file")

# Menggunakan Zenity untuk meminta input pengguna
nik=$(zenity --entry --title "Masukkan NIK" --text "NIK:")
nama=$(zenity --entry --title "Masukkan Nama" --text "Nama:")
tempat_lahir=$(zenity --entry --title "Masukkan Tempat Tanggal Lahir" --text "Tempat Tanggal Lahir:")
jenis_kelamin=$(zenity --entry --title "Masukkan Jenis Kelamin" --text "Jenis Kelamin:")
alamat=$(zenity --entry --title "Masukkan Alamat" --text "Alamat:")
agama=$(zenity --entry --title "Masukkan Agama" --text "Agama:")
status_perkawinan=$(zenity --entry --title "Masukkan Status Perkawinan" --text "Status Perkawinan:")
pekerjaan=$(zenity --entry --title "Masukkan Pekerjaan" --text "Pekerjaan:")
kewarganegaraan=$(zenity --entry --title "Masukkan Kewarganegaraan" --text "Kewarganegaraan:")
berlaku_hingga=$(zenity --entry --title "Masukkan Berlaku Hingga" --text "Berlaku Hingga:")

# Menyimpan data baru ke dalam berkas CSV
echo "$nik,$nama,$tempat_lahir,$jenis_kelamin,$alamat,$agama,$status_perkawinan,$pekerjaan,$kewarganegaraan,$berlaku_hingga" >> "$data_file"

# Menampilkan data dalam bentuk list Zenity dengan judul kolom
{
  echo "NIK|Nama|Tempat Tanggal Lahir|Jenis Kelamin|Alamat|Agama|Status Perkawinan|Pekerjaan|Kewarganegaraan|Berlaku Hingga"
  echo "$data_existing"
  echo "$nik|$nama|$tempat_lahir|$jenis_kelamin|$alamat|$agama|$status_perkawinan|$pekerjaan|$kewarganegaraan|$berlaku_hingga"
} | zenity --list --title "Data Anda" --text "Data Anda" --column "NIK" --column "Nama" --column "Tempat Tanggal Lahir" --column "Jenis Kelamin" --column "Alamat" --column "Agama" --column "Status Perkawinan" --column "Pekerjaan" --column "Kewarganegaraan" --column "Berlaku Hingga" --width 600 --height 400

exit 0
